In [1]:
import numpy as np
import tensorflow as tf
import keras
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("../L12-Gradient_Descent/insurance_data.csv")
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df[['bought_insurance']],test_size=0.2,random_state=25)

In [4]:
len(X_train)

22

In [5]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [6]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [7]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000
1/1 [==============================] - 0s 297ms/step - loss: 0.6663 - accuracy: 0.5000
Epoch 2/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6662 - accuracy: 0.5000
Epoch 3/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6661 - accuracy: 0.5000
Epoch 4/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6659 - accuracy: 0.5000
Epoch 5/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6658 - accuracy: 0.5000
Epoch 6/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6657 - accuracy: 0.5000
Epoch 7/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6655 - accuracy: 0.5000
Epoch 8/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6654 - accuracy: 0.5000
Epoch 9/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6653 - accuracy: 0.5000
Epoch 10/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6651 - accuracy: 0.5000
Epoch 11/5000


IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



1/1 [==============================] - 0s 1ms/step - loss: 0.4928 - accuracy: 0.8636
Epoch 2683/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4928 - accuracy: 0.8636
Epoch 2684/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4927 - accuracy: 0.8636
Epoch 2685/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.4927 - accuracy: 0.8636
Epoch 2686/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4927 - accuracy: 0.8636
Epoch 2687/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4926 - accuracy: 0.8636
Epoch 2688/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.4926 - accuracy: 0.8636
Epoch 2689/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4926 - accuracy: 0.8636
Epoch 2690/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4925 - accuracy: 0.8636
Epoch 2691/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.4925 - accuracy: 0.8636
Epo

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



1/1 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.8636
Epoch 3907/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.8636
Epoch 3908/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.8636
Epoch 3909/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.8636
Epoch 3910/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4589 - accuracy: 0.8636
Epoch 3911/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4589 - accuracy: 0.8636
Epoch 3912/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.4589 - accuracy: 0.8636
Epoch 3913/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4589 - accuracy: 0.8636
Epoch 3914/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4589 - accuracy: 0.8636
Epoch 3915/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.4588 - accuracy: 0.8636
Epoch 

In [8]:
model.evaluate(X_test_scaled,y_test)


1/1 [==============================] - 0s 93ms/step - loss: 0.3018 - accuracy: 1.0000


[0.3018476665019989, 1.0]

In [9]:
model.predict(X_test_scaled)


1/1 [==============================] - 0s 46ms/step


array([[0.7258772 ],
       [0.28684953],
       [0.14232635],
       [0.43514407],
       [0.7509663 ],
       [0.8680221 ]], dtype=float32)

In [10]:
y_test


bought_insurance
2                  1
10                 0
21                 0
11                 0
14                 1
9                  1

In [11]:
coef, intercept = model.get_weights()


In [12]:
coef, intercept


(array([[6.4984117],
        [1.4052392]], dtype=float32),
 array([-3.485688], dtype=float32))

In [13]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [14]:
X_test


age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [15]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

0.7258772077508672

In [16]:
prediction_function(.18, 1)


0.2868495279511965

In [17]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [18]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [19]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [23]:
gradient_descent(np.array( X_train_scaled['age']),np.array(X_train_scaled['affordibility']),np.array(y_train),1000, 0.4631)


Epoch:0, w1:[0.96941081 1.00978805 0.99724718 0.95787872 0.96022588 0.9708469
 0.95903712 1.01176983 0.96976694 0.99865745 0.99492209 1.01176983
 0.95845414 0.96144522 0.95675044 1.01476055 1.01077761 0.96175486
 0.96333198 0.95874468 0.96905662 0.96144522], w2:[0.95888887 1.02254668 1.00277504 0.94070765 0.94440812 0.96115297
 0.94253395 1.02567111 0.95945033 1.00499844 0.99910936 1.02567111
 0.94161484 0.94633051 0.93892882 1.03038621 1.0241068  0.94681868
 0.94930513 0.9420729  0.95833045 0.94633051], bias:-0.11341867736368583, loss:0.8508857779177963
Epoch:1, w1:[0.94479822 1.02507789 0.99995406 0.92176251 0.92648146 0.94764564
 0.92409382 1.0290598  0.94550467 1.00277356 0.99530824 1.0290598
 0.92292115 0.92892583 0.91948707 1.03507546 1.02706575 0.92954583
 0.9326995  0.92350573 0.94409537 0.92892583], w2:[0.9272003  1.05376736 1.01415771 0.89088274 0.89832253 0.93168948
 0.89455823 1.06004515 0.92831407 1.01860288 1.00683321 1.06004515
 0.89270943 0.90217627 0.88729533 1.0695292

(array([ 4.78853413, 49.11910585, 26.73954483,  3.99533431,  4.14802382,
         4.89654714,  4.0702476 , 56.31381554,  4.81508817, 28.22614484,
        24.58141218, 56.31381554,  4.03244306,  4.2288303 ,  3.92312874,
        71.88202107, 52.47626994,  4.24952626,  4.35612079,  4.05125714,
         4.76227137,  4.2288303 ]),
 array([ 14.08798379,  83.97852479,  48.69543309,  12.83744353,
         13.07817024,  14.25827457,  12.95555006,  95.32153556,
         14.12984825,  51.03917184,  45.2929717 ,  95.32153556,
         12.89594831,  13.20556784,  12.72360592, 119.86600373,
         89.27135105,  13.23819659,  13.40625105,  12.92561015,
         14.04657853,  13.20556784]),
 -14.729919714212897)

In [21]:
coef, intercept


(array([[6.4984117],
        [1.4052392]], dtype=float32),
 array([-3.485688], dtype=float32))

In [88]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y,epochs,loss_thresold )

        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test.age + self.w2*X_test.affordibility + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [89]:
customModel = myNN()
customModel.fit(X_train_scaled,y_train, epochs=8000, loss_thresold=0.4631)

ValueError: Unable to coerce to Series, length must be 1: given 22