In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)


[28, 27]

In [16]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[7, 22],
 [28, 27],
 [12, 20],
 [18, 28, 1],
 [24, 14, 7],
 [3, 22],
 [22, 14, 14],
 [4, 1],
 [4, 20],
 [19, 14]]

In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 7 22  0  0]
 [28 27  0  0]
 [12 20  0  0]
 [18 28  1  0]
 [24 14  7  0]
 [ 3 22  0  0]
 [22 14 14  0]
 [ 4  1  0  0]
 [ 4 20  0  0]
 [19 14  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)


In [10]:
loss, accuracy = model.evaluate(X, y)
accuracy


1/1 [==============================] - 0s 102ms/step - loss: 0.6288 - accuracy: 1.0000


1.0

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [18]:
weights[7]
#word  nice

array([ 0.05877236, -0.10061254, -0.01399781,  0.06685279, -0.07991663],
      dtype=float32)

In [19]:
weights[28]
#word amazing

array([-0.05116009, -0.09770481, -0.0611932 ,  0.05887438, -0.04234425],
      dtype=float32)

In [20]:
#word nice and amazing have an similar weights as they refer to the same meaning
#if the data is big they will be more similar

In [22]:
weights[4]
#word poor

array([ 0.07006485,  0.09350241,  0.04871524, -0.09367947,  0.05082468],
      dtype=float32)